### PR TITLE
For heruko niggas

### PR DESCRIPTION
**Pull request by annihilatorrrr**
///

### CODE REVIEW

**Review by TheHamkerCat — CHANGES_REQUESTED** [review]
Change it back to sample_config.py, this isn't  good, .gitignore has config.py

**Review by TheHamkerCat — CHANGES_REQUESTED** [review]
Bad, what about local desktop and VPSs? they use config.py

**Comment by annihilatorrrr** [comment]
> Bad, what about local desktop and VPSs? they use config.py

ooo w8

**Review by TheHamkerCat — CHANGES_REQUESTED** [review]
What about config.py

**Comment by annihilatorrrr** [comment]
i don't understand why using did u tell to rename back the config to sample_config,

https://github.com/TheHamkerCat/LunaChatBot/blob/9568b3654c5e6a2b93655fffdd844d65beaa36e9/.gitignore#L1

**Comment by TheHamkerCat** [comment]
When did i?

**Comment by annihilatorrrr** [comment]
> When did i?

https://github.com/TheHamkerCat/LunaChatBot/pull/7#pullrequestreview-730126259

**Comment by TheHamkerCat** [comment]
> > When did i?
> 
> [#7 (review)](https://github.com/TheHamkerCat/LunaChatBot/pull/7#pullrequestreview-730126259)

Because you changed sample_config.py to config.py,

Both files should exist, and the code in luna.py should only import vars from config.py

**Comment by annihilatorrrr** [comment]
> > > When did i?
> > 
> > 
> > [#7 (review)](https://github.com/TheHamkerCat/LunaChatBot/pull/7#pullrequestreview-730126259)
> 
> Because you changed sample_config.py to config.py,
> 
> Both files should exist, and the code in luna.py should only import vars from config.py

oke w8

**Comment by TheHamkerCat** [comment]
Let's fix it tomorrow, use the same method which wbb and tgvcbot uses for heroku, importing sample_config **and** config.py, whichever is available.

**Comment by annihilatorrrr** [comment]
| Luna Started! |

**Comment by Tejas61900** [comment]
24 commits 😵‍💫
CLI never ?

**Comment by annihilatorrrr** [comment]
> 24 commits 😵‍💫
> CLI never ?

Nah 🥲

**Comment by annihilatorrrr** [comment]
f, i could not remove those 28 commits before

**Comment by annihilatorrrr** [comment]
bak bici , my bad i should test before creating a pull req.

should i close this someone else will do or create a new (ig not) or quit it

**Comment by TheHamkerCat** [comment]
> f, i could not remove those 28 commits before

why not?

**Comment by annihilatorrrr** [comment]
> > f, i could not remove those 28 commits before
> 
> why not?
i squashed but forgot to remove earlier commits and did git push and created 30 commits (dublicates) after that i don't know to use git bash well :(

**Comment by Tejas61900** [comment]
> > > f, i could not remove those 28 commits before
> > 
> > 
> > why not?
> > i squashed but forgot to remove earlier commits and did git push and created 30 commits (dublicates) after that i don't know to use git bash well :(

Ahhhh , Use Linux or use Gcloud shell or even u can use git in Termux

**Comment by TheHamkerCat** [comment]
F

**Pull request closed without merging**
